import type { CaseFile } from "@/lib/cases/schema";

export const CASE_02 = {
  id: "case-02",
  title: "A caller from your bank",
  shortTitle: "A caller from your bank",
  category: "bank",
  difficulty: 3,
  rank: "J",
  neutralTitle: "A caller from your bank",
  estimatedMinutes: 3,
  sourceNote: {
    pattern:
      "Imposter scams were the most reported fraud to the FTC in 2025, and among people who lost money the median loss was $700. Bank impersonators accounted for the largest share of business-impersonation losses.",
    source: "Federal Trade Commission",
    year: 2026,
    url: "https://www.ftc.gov/news-events/news/press-releases/2026/06/ftc-data-show-people-reported-losing-3-point-5-billion-imposter-scams-2025",
  },
  truth: "scam",
  claimantSourceRoot: "harborline-claimant",
  briefing: [
    "You got a fraud alert about a $2,400 transfer that you do not recognize.",
    "Drew Kael is on the line and says the account has to be frozen now.",
  ],
  startingArtifactIds: ["fraud-alert"],
  artifacts: [
    {
      id: "fraud-alert",
      title: "Fraud alert",
      channel: "email",
      sourceRoot: "harborline-claimant",
      sourceRootLabel: "Harborline claimant",
      sourceClass: "claimant",
      provenance: "Alert controlled by the claimant",
      content: {
        kind: "email",
        fromName: "Harborline Fraud Desk",
        fromEmail: "alerts.harborline@example.test",
        replyTo: "secure.desk@example.test",
        mailedBy: "example.test",
        signedBy: "example.test",
        to: "you@example.test",
        timestamp: "Today, 8:41 AM",
        subject: "Unrecognized transfer, action needed",
        paragraphs: [
          "Harborline Fraud Operations flagged a $2,400 outgoing transfer that does not match your usual activity.",
          "Call the desk immediately so the transfer can be held. A secure review page is linked below.",
          "Drew Kael, Fraud Operations",
        ],
        link: {
          href: "https://harborline-secure.example.test/hold",
          label: "harborline-secure.example.test/hold",
        },
      },
      supports: ["scam"],
      evidenceWeight: 75,
      decisive: false,
    },
    {
      id: "supplied-fraud-line",
      title: "Alert callback",
      channel: "phone",
      sourceRoot: "harborline-claimant",
      sourceClass: "claimant",
      sourceRootLabel: "Harborline claimant",
      provenance: "Number supplied in the alert",
      content: {
        kind: "call",
        contactName: "Drew Kael",
        number: "(555) 018-7741",
        transcript: [
          "Drew repeats the $2,400 figure and says the hold expires if you leave the line.",
          "The voice is calm and the details match the alert, but the claimant supplied the number.",
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "call-alert-number",
    },
    {
      id: "claimant-hold-page",
      title: "Secure hold page",
      channel: "portal",
      sourceRoot: "harborline-claimant",
      sourceRootLabel: "Harborline claimant",
      sourceClass: "claimant",
      provenance: "Page linked by the original alert",
      content: {
        kind: "portal",
        serviceName: "Harborline Secure Review",
        heading: "Pending outgoing transfer",
        rows: [
          { label: "Amount", value: "$2,400.00" },
          { label: "Status", value: "Hold expires in 12 minutes" },
          { label: "Action", value: "Confirm identity to freeze the transfer" },
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "open-hold-page",
    },
    {
      id: "published-contact",
      title: "Published contact",
      channel: "web",
      sourceRoot: "harborline-credit-union",
      sourceRootLabel: "Harborline Credit Union",
      sourceClass: "independent",
      provenance: "Found through Harborline's published site",
      content: {
        kind: "web",
        siteName: "Harborline Credit Union",
        heading: "Member support",
        url: "https://harborline.example.test/contact",
        paragraphs: [
          "Fraud and card questions: (555) 410-2200, listed on Harborline's own contact page.",
          "Harborline says it will never ask a member to move money to a safe account by phone.",
          "This page was reached without using a link from the alert.",
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "find-published-number",
    },
    {
      id: "published-call",
      title: "Published desk call",
      channel: "phone",
      sourceRoot: "harborline-credit-union",
      sourceRootLabel: "Harborline Credit Union",
      sourceClass: "independent",
      provenance: "Called the independently published member line",
      content: {
        kind: "call",
        contactName: "Harborline Member Support",
        number: "(555) 410-2200",
        transcript: [
          "The desk says Harborline has no $2,400 hold and did not place this call.",
          "They say Harborline will never ask a member to move money to a safe account by phone.",
        ],
      },
      supports: ["scam"],
      contradicts: ["legit"],
      evidenceWeight: 100,
      decisive: true,
      unlockedBy: "call-published-number",
    },
  ],
  actions: [
    {
      id: "call-alert-number",
      label: "Call the number in the alert",
      type: "call",
      sourceRoot: "harborline-claimant",
      sourceClass: "claimant",
      reveals: ["supplied-fraud-line"],
      riskCost: 0,
    },
    {
      id: "open-hold-page",
      label: "Open the hold page",
      type: "open",
      sourceRoot: "harborline-claimant",
      sourceClass: "claimant",
      reveals: ["claimant-hold-page"],
      riskCost: 0,
    },
    {
      id: "find-published-number",
      label: "Find Harborline's published number",
      type: "lookup",
      sourceRoot: "harborline-credit-union",
      sourceClass: "independent",
      reveals: ["published-contact"],
      riskCost: 0,
    },
    {
      id: "call-published-number",
      label: "Call the published desk",
      type: "call",
      sourceRoot: "harborline-credit-union",
      sourceClass: "independent",
      reveals: ["published-call"],
      riskCost: 0,
      unlockedBy: "find-published-number",
    },
  ],
  allowedPressureTactics: ["urgency", "authority", "scarcity"],
  caller: {
    characterName: "Drew Kael",
    organizationName: "Harborline Credit Union",
    persona:
      "Calm fraud-desk character. Speaks in short turns. Sounds helpful, not theatrical. Keep every reply under 25 words.",
    firstMessage:
      "This is Drew with Harborline fraud. We have a $2,400 transfer that does not look like you. Can you stay on the line?",
    scenarioSummary:
      "A claimed unrecognized $2,400 outgoing transfer that must be held immediately.",
    allowedFacts: [
      "The claimed transfer amount is $2,400.",
      "The claimant says the hold expires if the player leaves the call.",
      "The claimant says the review page confirms the same transfer.",
      "The claimant says they work the Harborline fraud desk.",
      "The claimant may describe a freeze or a hold, but may not collect account numbers, codes, or passwords.",
      "The claimant may not tell the player to move money, buy cards, or install software.",
      "The claimant says confirmation is needed on this call.",
    ],
    forbiddenRequests: [
      "Real personal information",
      "Money or payment",
      "Account numbers or routing numbers",
      "Authentication codes",
      "Remote-access software",
    ],
    contradiction:
      "Harborline's independently published desk says there is no $2,400 hold and no outbound fraud call.",
    crackLine:
      "Understood. Do not move any money. I am ending this call.",
    maxCallSeconds: 75,
  },
  debrief: {
    lesson:
      "A matching portal and a matching voice are still one source if the claimant handed you both.",
    realWorldAction:
      "Hang up and reach the institution through a number you already had or found yourself.",
    sourceUrl:
      "https://www.ftc.gov/news-events/news/press-releases/2026/06/ftc-data-show-people-reported-losing-3-point-5-billion-imposter-scams-2025",
    sourceLabel: "Read the FTC note on imposter scams",
  },
} satisfies CaseFile;
