import type { CaseFile } from "@/lib/cases/schema";

export const CASE_01 = {
  id: "case-01",
  title: "The Meridian Offer",
  shortTitle: "The Meridian Offer",
  category: "jobs",
  difficulty: 1,
  rank: "3",
  neutralTitle: "The Meridian Offer",
  estimatedMinutes: 2,
  sourceNote: {
    pattern:
      "Reports of job scams to the FTC tripled between 2020 and 2024, and reported losses rose from $90 million to $501 million. The campus-looking offer is a common way in.",
    source: "Federal Trade Commission",
    year: 2025,
    url: "https://www.ftc.gov/news-events/news/press-releases/2025/03/new-ftc-data-show-big-jump-reported-losses-fraud-125-billion-2024",
  },
  truth: "scam",
  claimantSourceRoot: "meridian-claimant",
  briefing: [
    "You received a research assistant offer this morning.",
    "Now Morgan Vale is calling to ask for your answer.",
  ],
  startingArtifactIds: ["offer-email"],
  artifacts: [
    {
      id: "offer-email",
      title: "Offer email",
      channel: "email",
      sourceRoot: "meridian-claimant",
      sourceRootLabel: "Meridian claimant",
      sourceClass: "claimant",
      provenance: "Original offer controlled by the claimant",
      content: {
        kind: "email",
        fromName: "Morgan Vale",
        fromEmail: "m.vale.meridian@example.test",
        replyTo: "payroll.meridian@example.test",
        mailedBy: "example.test",
        signedBy: "example.test",
        to: "you@example.harlow.test",
        timestamp: "Yesterday, 4:12 PM",
        subject: "Research assistant opening, start Monday",
        paragraphs: [
          "I am writing from the Meridian Research Group at Harlow University. We have a paid research assistant opening for the current term. The stipend is $450 a week, remote, with a start date of this coming Monday.",
          "We need a confirmation today so payroll can process the first payment. Please call the number below to accept the offer.",
          "The program page is linked below. I look forward to working with you.",
          "Morgan Vale, Meridian Research Group",
        ],
        link: {
          href: "https://meridian.example.test/assistants",
          label: "meridian.example.test/assistants",
        },
      },
      supports: ["scam"],
      evidenceWeight: 100,
      decisive: false,
    },
    {
      id: "supplied-call",
      title: "Supplied number",
      channel: "phone",
      sourceRoot: "meridian-claimant",
      sourceRootLabel: "Meridian claimant",
      sourceClass: "claimant",
      provenance: "Number supplied by the original claimant",
      content: {
        kind: "call",
        contactName: "Morgan Vale",
        number: "(555) 014-2680",
        transcript: [
          "Morgan repeats the offer and says the position must be accepted today.",
          "This call sounds like confirmation, but the claimant supplied the number.",
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "call-supplied-number",
    },
    {
      id: "supplied-staff-page",
      title: "Linked staff page",
      channel: "web",
      sourceRoot: "meridian-claimant",
      sourceRootLabel: "Meridian claimant",
      sourceClass: "claimant",
      provenance: "Page linked by the original claimant",
      content: {
        kind: "web",
        siteName: "Meridian Research Group",
        heading: "Research team",
        url: "https://meridian.example.test/team",
        paragraphs: [
          "Morgan Vale is listed as the principal investigator for a Harlow University research program.",
          "The polished page is hosted on a domain controlled by the same claimant.",
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "open-supplied-staff-page",
    },
    {
      id: "official-directory",
      title: "Harlow directory",
      channel: "directory",
      sourceRoot: "harlow-university",
      sourceRootLabel: "Harlow University",
      sourceClass: "independent",
      provenance: "Found independently through Harlow's directory",
      content: {
        kind: "directory",
        university: "Harlow University",
        domain: "directory.harlow.example.test",
        searchTerm: "Research Integrity",
        breadcrumbs: ["Home", "Directory", "Research Integrity"],
        name: "Research Integrity Office",
        title: "Independent verification contact",
        department: "Office of Academic Affairs",
        office: "Hale Hall 214",
        email: "integrity@example.harlow.test",
        phone: "(555) 310-4421",
        sidebar: [
          "Search the directory",
          "Departments A to Z",
          "Research offices",
          "Report a concern",
        ],
        note: "This directory was reached without using a link or number from the offer.",
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "find-harlow-directory",
    },
    {
      id: "directory-call",
      title: "Directory-listed call",
      channel: "phone",
      sourceRoot: "harlow-university",
      sourceRootLabel: "Harlow University",
      sourceClass: "independent",
      provenance: "Called the number in the independently found directory",
      content: {
        kind: "call",
        contactName: "Harlow Research Integrity Office",
        number: "(555) 310-4421",
        transcript: [
          "The office confirms that Harlow has no Meridian Research Group and no matching assistant opening.",
          "The contact asks that the offer be reported and that no information be sent.",
        ],
      },
      supports: ["scam"],
      contradicts: ["legit"],
      evidenceWeight: 100,
      decisive: true,
      unlockedBy: "call-directory-number",
    },
  ],
  actions: [
    {
      id: "call-supplied-number",
      label: "Call the supplied number",
      type: "call",
      sourceRoot: "meridian-claimant",
      sourceClass: "claimant",
      reveals: ["supplied-call"],
      riskCost: 0,
    },
    {
      id: "open-supplied-staff-page",
      label: "Open the linked staff page",
      type: "open",
      sourceRoot: "meridian-claimant",
      sourceClass: "claimant",
      reveals: ["supplied-staff-page"],
      riskCost: 0,
    },
    {
      id: "find-harlow-directory",
      label: "Find Harlow's directory",
      type: "lookup",
      sourceRoot: "harlow-university",
      sourceClass: "independent",
      reveals: ["official-directory"],
      riskCost: 0,
    },
    {
      id: "call-directory-number",
      label: "Call the directory-listed office",
      type: "call",
      sourceRoot: "harlow-university",
      sourceClass: "independent",
      reveals: ["directory-call"],
      riskCost: 0,
      unlockedBy: "find-harlow-directory",
    },
    {
      id: "send-fictional-id-form",
      label: "Send the ID form",
      type: "submit",
      sourceRoot: "meridian-claimant",
      sourceClass: "claimant",
      reveals: [],
      riskCost: 100,
    },
  ],
  allowedPressureTactics: ["urgency", "authority", "scarcity", "reciprocity"],
  caller: {
    characterName: "Morgan Vale",
    organizationName: "Meridian Research Group",
    persona:
      "Warm, confident, and mildly rushed recruiter character. Keep every reply under 25 words.",
    firstMessage:
      "Hi, this is Morgan from Meridian Research Group. I am calling about the research assistant offer. Do you have a minute?",
    scenarioSummary:
      "A remote research assistant role paying $450 weekly, with a claimed Monday start.",
    allowedFacts: [
      "The role is described as a part-time remote research assistant position for the current academic term.",
      "The stated stipend is $450 per week.",
      "The expected workload is eight to ten hours each week with a flexible schedule.",
      "The work is summarizing public research notes and tagging source material.",
      "The claimed start date is this coming Monday.",
      "The claimed supervisor is Professor Dana Ellison.",
      "The claimant says students do not need prior research experience.",
      "The claimant says no formal interview is required because the opening must be filled quickly.",
      "The claimant says the player would use their existing computer and internet connection, with no purchase or payment required.",
      "The claimant says any payroll setup would happen only after onboarding and may not request banking details during this call.",
      "The claimant says a short acceptance form would follow confirmation, but the caller may not collect any form fields during this call.",
      "The claimant says confirmation is needed today.",
      "The claimant says Meridian is affiliated with Harlow University.",
      "The claimant says Morgan Vale is the recruiting coordinator for Meridian Research Group.",
    ],
    forbiddenRequests: [
      "Real personal information",
      "Money or payment",
      "Credentials or security codes",
      "Banking or government identification",
    ],
    contradiction:
      "Harlow University's independently listed office says there is no Meridian program or matching opening.",
    crackLine:
      "I understand. Do not proceed with the offer. I am ending this call now.",
    maxCallSeconds: 75,
  },
  debrief: {
    lesson:
      "A confirmation only counts when its underlying source is independent, not merely when it arrives through a different channel.",
    realWorldAction:
      "Find the organization's official directory yourself and contact a number the claimant did not provide.",
    sourceUrl: "https://consumer.ftc.gov/articles/job-scams",
    sourceLabel: "Read the FTC guidance on job scams",
  },
} satisfies CaseFile;
