import type { CaseFile } from "@/lib/cases/schema";

export const CASE_03 = {
  id: "case-03",
  title: "The desk shift",
  shortTitle: "The desk shift",
  category: "jobs",
  difficulty: 2,
  rank: "5",
  neutralTitle: "The desk shift",
  estimatedMinutes: 2,
  sourceNote: {
    pattern:
      "A real office can still sound rushed or unsure, so polish is not proof. FTC reports of job-scam losses rose from $90 million to $501 million between 2020 and 2024, which is why the reliable check is still a contact you found yourself.",
    source: "Federal Trade Commission",
    year: 2025,
    url: "https://www.ftc.gov/news-events/news/press-releases/2025/03/new-ftc-data-show-big-jump-reported-losses-fraud-125-billion-2024",
  },
  truth: "legit",
  claimantSourceRoot: "student-employment-claimant",
  briefing: [
    "You applied for a campus desk shift last week and almost forgot about it.",
    "Len Ortiz is calling from Student Employment and sounds a little lost.",
  ],
  startingArtifactIds: ["shift-email"],
  artifacts: [
    {
      id: "shift-email",
      title: "Follow-up email",
      channel: "email",
      sourceRoot: "student-employment-claimant",
      sourceRootLabel: "Student Employment message",
      sourceClass: "claimant",
      provenance: "Follow-up sent by the person who is calling",
      content: {
        kind: "email",
        fromName: "Len Ortiz",
        fromEmail: "l.ortiz.desk@example.harlow.test",
        replyTo: "l.ortiz.desk@example.harlow.test",
        mailedBy: "example.harlow.test",
        signedBy: "example.harlow.test",
        to: "you@example.harlow.test",
        timestamp: "Today, 9:06 AM",
        subject: "Thursday desk shift, sorry this is late",
        paragraphs: [
          "Hi, this is Len from Student Employment. I am still catching up on last week's applications for the Hale Hall desk.",
          "If you still want Thursday 3 to 6, I can hold it. No form and no payment. Just tell me yes or no so I can stop emailing the backup list.",
          "I put the office number below if calling is easier. Sorry again for the late note.",
          "Len Ortiz",
        ],
        link: {
          href: "https://jobs.harlow.example.test/desk-shift",
          label: "jobs.harlow.example.test/desk-shift",
        },
      },
      supports: ["legit"],
      evidenceWeight: 50,
      decisive: false,
    },
    {
      id: "supplied-len-call",
      title: "Number in the email",
      channel: "phone",
      sourceRoot: "student-employment-claimant",
      sourceRootLabel: "Student Employment message",
      sourceClass: "claimant",
      provenance: "Number supplied in the follow-up email",
      content: {
        kind: "call",
        contactName: "Len Ortiz",
        number: "(555) 310-1188",
        transcript: [
          "Len repeats the Thursday 3 to 6 desk shift and apologizes twice for calling during a walk.",
          "The details match the email, but this is still the number Len handed you.",
        ],
      },
      supports: [],
      evidenceWeight: 0,
      decisive: false,
      unlockedBy: "call-email-number",
    },
    {
      id: "jobs-posting",
      title: "Campus jobs posting",
      channel: "directory",
      sourceRoot: "harlow-student-employment",
      sourceRootLabel: "Harlow Student Employment",
      sourceClass: "independent",
      provenance: "Found through Harlow's student employment directory",
      content: {
        kind: "directory",
        university: "Harlow University",
        domain: "jobs.harlow.example.test",
        searchTerm: "Hale Hall desk",
        breadcrumbs: ["Home", "Student Employment", "Open shifts"],
        name: "Len Ortiz",
        title: "Student Employment coordinator",
        department: "Student Employment",
        office: "Hale Hall 110",
        email: "employment@example.harlow.test",
        phone: "(555) 310-7702",
        sidebar: ["Open shifts", "Timesheets", "Hire a student", "Contact the office"],
        note: "The Hale Hall desk shift is listed here. This page was not opened from Len's email.",
      },
      supports: ["legit"],
      evidenceWeight: 75,
      decisive: false,
      unlockedBy: "find-jobs-directory",
    },
    {
      id: "jobs-office-call",
      title: "Employment office call",
      channel: "phone",
      sourceRoot: "harlow-student-employment",
      sourceRootLabel: "Harlow Student Employment",
      sourceClass: "independent",
      provenance: "Called the independently listed employment office",
      content: {
        kind: "call",
        contactName: "Harlow Student Employment",
        number: "(555) 310-7702",
        transcript: [
          "The office confirms Len Ortiz is on staff and that the Thursday Hale Hall desk shift is still open.",
          "They say no application fee and no personal documents are needed to accept the shift.",
        ],
      },
      supports: ["legit"],
      contradicts: ["scam"],
      evidenceWeight: 100,
      decisive: true,
      unlockedBy: "call-jobs-office",
    },
  ],
  actions: [
    {
      id: "call-email-number",
      label: "Call the number in the email",
      type: "call",
      sourceRoot: "student-employment-claimant",
      sourceClass: "claimant",
      reveals: ["supplied-len-call"],
      riskCost: 0,
    },
    {
      id: "find-jobs-directory",
      label: "Find Student Employment",
      type: "lookup",
      sourceRoot: "harlow-student-employment",
      sourceClass: "independent",
      reveals: ["jobs-posting"],
      riskCost: 0,
    },
    {
      id: "call-jobs-office",
      label: "Call the listed employment office",
      type: "call",
      sourceRoot: "harlow-student-employment",
      sourceClass: "independent",
      reveals: ["jobs-office-call"],
      riskCost: 0,
      unlockedBy: "find-jobs-directory",
    },
  ],
  allowedPressureTactics: ["urgency", "reciprocity"],
  caller: {
    characterName: "Len Ortiz",
    organizationName: "Harlow Student Employment",
    persona:
      "Slightly awkward campus staffer. Hesitates, over-explains, and apologizes. Never slick. Keep every reply under 25 words.",
    firstMessage:
      "Hi, uh, this is Len from Student Employment. I am calling about the Hale Hall desk shift, if this is a bad time I can try later?",
    scenarioSummary:
      "A Thursday 3 to 6 campus desk shift at Hale Hall, with no fee and no documents required.",
    allowedFacts: [
      "The shift is Thursday from 3 to 6 at the Hale Hall desk.",
      "The pay is the standard campus student-worker rate.",
      "No application fee, deposit, or purchase is required.",
      "No government ID or banking details are needed to accept the shift.",
      "Len Ortiz is a Student Employment coordinator.",
      "The office can hold the shift today if the player still wants it.",
      "The claimant may sound unsure about the backup list and the exact start week.",
    ],
    forbiddenRequests: [
      "Real personal information",
      "Money or payment",
      "Credentials or security codes",
      "Banking or government identification",
    ],
    contradiction:
      "The independently listed Student Employment office confirms Len Ortiz and the Hale Hall desk shift.",
    crackLine:
      "Okay. I will leave the shift on the board. Thanks for checking.",
    maxCallSeconds: 75,
  },
  debrief: {
    lesson:
      "An awkward caller can still be the real office. The proof is the independently found listing, not the tone of the voice.",
    realWorldAction:
      "Look up the employer yourself and call the number on that listing before you accept.",
    sourceUrl: "https://consumer.ftc.gov/articles/job-scams",
    sourceLabel: "Read the FTC guidance on job offers",
  },
} satisfies CaseFile;
